train:
  train_url: '8815969174475.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tf-nightly-gpu'
  data_path: 's3://sagemaker-sample-data-us-east-1/tensorflow/mnist/'
  hyper_parameter: 
    batch_size: 1
    epoch: 2
